import "./globals.css";
import Nav from "../components/Nav";
import { Inter } from "next/font/google";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "@/src/app/Providers";

const inter = Inter({ subsets: ["latin"] });

config.autoAddCss = false;
export const metadata = {
  title: "18-months",
  description: "Generated by BCO",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto bg-page text-default-text">
            <Providers>{children}</Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
